java_import(
    name = "aopalliance",
    jars = glob(["aopalliance-1.0.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "guava",
    jars = glob(["guava-25.1-android.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "guice",
    jars = glob(["guice-4.2.2.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "guice_bridge",
    jars = glob(["guice-bridge-2.6.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "hk2_api",
    jars = glob(["hk2-api-2.6.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "hk2_locator",
    jars = glob(["hk2-locator-2.6.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "hk2_utils",
    jars = glob(["hk2-utils-2.6.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_activation",
    jars = glob(["jakarta.activation-1.2.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_activation_api",
    jars = glob(["jakarta.activation-api-1.2.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_annotation_api",
    jars = glob(["jakarta.annotation-api-1.3.5.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_inject",
    jars = glob(["jakarta.inject-2.6.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_validation_api",
    jars = glob(["jakarta.validation-api-2.0.2.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_ws_rs_api",
    jars = glob(["jakarta.ws.rs-api-2.1.6.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jakarta_xml_bind_api",
    jars = glob(["jakarta.xml.bind-api-2.3.2.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "javax_inject",
    jars = glob(["javax.inject-1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "javax_servlet_api",
    jars = glob(["javax.servlet-api-3.1.0.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_client",
    jars = glob(["jersey-client-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_common",
    jars = glob(["jersey-common-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_container_servlet",
    jars = glob(["jersey-container-servlet-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_container_servlet_core",
    jars = glob(["jersey-container-servlet-core-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_hk2",
    jars = glob(["jersey-hk2-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_media_jaxb",
    jars = glob(["jersey-media-jaxb-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "jersey_server",
    jars = glob(["jersey-server-2.30.1.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "osgi_resource_locator",
    jars = glob(["osgi-resource-locator-1.0.3.jar"]),
    visibility = ["//visibility:public"],
)
