java_library(
    name = "service",
    srcs = glob(
        ["**/*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:guice",
        "//lib:javax_inject",
    ],
)
