java_library(
    name = "resource",
    srcs = glob(
        ["**/*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:guice",
        "//lib:jakarta_ws_rs_api",
        "//lib:javax_inject",
        "//main/java/com/feedwheel/service",
    ],
)
